In [98]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [99]:
data = pd.read_csv("diabetes2.csv")
data

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [100]:
data = pd.read_csv("diabetes2.csv")
data

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [101]:
data.corr()

Pregnancies   Glucose  BloodPressure  SkinThickness  \
Pregnancies                  1.000000  0.129459       0.141282      -0.081672   
Glucose                      0.129459  1.000000       0.152590       0.057328   
BloodPressure                0.141282  0.152590       1.000000       0.207371   
SkinThickness               -0.081672  0.057328       0.207371       1.000000   
Insulin                     -0.073535  0.331357       0.088933       0.436783   
BMI                          0.017683  0.221071       0.281805       0.392573   
DiabetesPedigreeFunction    -0.033523  0.137337       0.041265       0.183928   
Age                          0.544341  0.263514       0.239528      -0.113970   
Outcome                      0.221898  0.466581       0.065068       0.074752   

                           Insulin       BMI  DiabetesPedigreeFunction  \
Pregnancies              -0.073535  0.017683                 -0.033523   
Glucose                   0.331357  0.221071                  0.137337   
BloodPressure             0.088933  0.281805                  0.041265   
SkinThickness             0.436783  0.392573                  0.183928   
Insulin                   1.000000  0.197859                  0.185071   
BMI                       0.197859  1.000000                  0.140647   
DiabetesPedigreeFunction  0.185071  0.140647                  1.000000   
Age                      -0.042163  0.036242                  0.033561   
Outcome                   0.130548  0.292695                  0.173844   

                               Age   Outcome  
Pregnancies               0.544341  0.221898  
Glucose                   0.263514  0.466581  
BloodPressure             0.239528  0.065068  
SkinThickness            -0.113970  0.074752  
Insulin                  -0.042163  0.130548  
BMI                       0.036242  0.292695  
DiabetesPedigreeFunction  0.033561  0.173844  
Age                       1.000000  0.238356  
Outcome                   0.238356  1.000000

In [102]:
X = data.drop("Outcome", axis = 1)
Y = data["Outcome"]


In [103]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.2, random_state=42)

In [104]:
x_train.shape

(614, 8)

In [105]:
y_train.shape

(614,)

In [106]:
type(y_train)

pandas.core.series.Series

In [107]:
type(x_train)

pandas.core.frame.DataFrame

# Standerdization

In [108]:
from sklearn.preprocessing import StandardScaler
 
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [109]:
x_train

array([[-0.52639686, -1.15139792, -3.75268255, ..., -4.13525578,
        -0.49073479, -1.03594038],
       [ 1.58804586, -0.27664283,  0.68034485, ..., -0.48916881,
         2.41502991,  1.48710085],
       [-0.82846011,  0.56687102, -1.2658623 , ..., -0.42452187,
         0.54916055, -0.94893896],
       ...,
       [ 1.8901091 , -0.62029661,  0.89659009, ...,  1.76054443,
         1.981245  ,  0.44308379],
       [-1.13052335,  0.62935353, -3.75268255, ...,  1.34680407,
        -0.78487662, -0.33992901],
       [-1.13052335,  0.12949347,  1.43720319, ..., -1.22614383,
        -0.61552223, -1.03594038]])

In [110]:
x_test

array([[ 0.49124165, -0.72667791, -0.44147615, ...,  0.23374785,
        -0.17094071,  0.66661154],
       [-0.63368347, -0.28534901,  0.31890843, ...,  0.43537945,
        -1.08608042, -1.07335756],
       [-0.63368347, -0.41144298, -0.17310512, ..., -0.14579397,
        -1.05362866, -1.07335756],
       ...,
       [ 1.05370422, -0.82124838,  0.18472291, ...,  0.56584695,
         0.00754398,  1.77386461],
       [-0.63368347,  0.78644972,  0.09526591, ..., -0.47789306,
        -0.47274211, -0.44064153],
       [ 1.05370422, -1.48324172,  0.09526591, ...,  0.38793672,
         0.72148276,  0.35025352]])

# Model Building

In [111]:
def sigmoid(z):
    return 1.0/(1.0+np.exp(-z))

In [112]:
z = np.array([0.5,0.5])
sigmoid(z)

array([0.62245933, 0.62245933])

In [113]:
def model_output(x,y,w,b):
    m = len(y)
    f_wb = np.zeros(m)
    f_wb = np.dot(x,w) + b
    z = sigmoid(f_wb)
    return z

In [114]:
x_train.shape

(614, 8)

In [115]:
W = np.array([1,1,1,1,1,1,1,1])
print(model_output(x_train,y_train,W,1))

[5.46911946e-06 9.97367038e-01 1.93250971e-01 2.49584364e-01
 9.99799845e-01 1.80179099e-01 3.71797176e-03 9.90380065e-01
 7.80956431e-01 7.18803959e-04 3.70470506e-01 8.44264878e-01
 6.36376386e-02 8.24721818e-01 9.17436361e-01 8.77479359e-01
 5.89745697e-01 6.36190566e-01 1.39628924e-01 9.99764407e-01
 9.99961525e-01 4.92394588e-01 3.79635559e-01 9.96277973e-01
 9.55870274e-01 4.63129014e-01 9.96132670e-01 9.88953738e-01
 6.89226424e-01 9.87217224e-01 9.98698874e-01 1.87385760e-01
 6.38889407e-02 3.54165772e-01 9.28885731e-01 9.97131189e-01
 1.00721919e-01 2.49646800e-02 9.24472076e-01 9.34616705e-01
 5.39248728e-01 1.50727654e-01 2.97101396e-03 3.46030299e-02
 5.88660014e-01 9.83160998e-01 4.33359022e-01 4.88222861e-01
 9.29247091e-01 9.83154453e-01 9.61588108e-01 3.37356112e-01
 1.58828648e-01 6.41940843e-01 9.99629497e-01 9.99278598e-01
 9.03292868e-01 6.55669988e-02 2.36732903e-01 3.71601704e-02
 9.99701907e-01 3.11277667e-02 9.99953311e-01 7.59832066e-01
 3.42349411e-01 9.354488

In [136]:
y_train = np.array(y_train)

In [137]:
def compute_cost(x,y,w,b):
    m = len(y)
    cost = 0
    for i in range(0,m):
        z_i =  np.dot(x[i],W) + b
        #print(type(z_i))
        f_wb_i = sigmoid(z_i)
        cost = cost + (-y[i]*np.log(f_wb_i) - (1-y[i])*np.log(1 - f_wb_i))
        return cost/m

In [138]:
print(compute_cost(x_train,y_train,W,1))
#x_train.shape

8.907385043790308e-09


In [164]:
def compute_decent(x,y,w,b):
    m,n = x.shape
    dj_dw = np.zeros((n,))
    dj_db = 0
    for i in range(0,m):
        f_wb = sigmoid(np.dot(x[i],w) +b)
        err = f_wb - y[i]
        for j in range(0,n):
            dj_dw[j] = dj_dw[j] + err*x[i][j]
        dj_db = dj_db + err
    dj_dw = dj_dw/m                                   
    dj_db = dj_db/m 
    return dj_db, dj_dw 

In [165]:
print(compute_decent(x_train,y_train,W,1))


(0.22656872857804078, array([ 0.06877293, -0.0167091 ,  0.140156  ,  0.14449899,  0.10518139,
        0.05115178,  0.04844718,  0.04853731]))


In [177]:
def gradient_descent(X, y, w_in, b_in, alpha, num_iters): 
    
    w = w_in  #avoid modifying global w within function
    b = b_in
    
    for i in range(num_iters):
        # Calculate the gradient and update the parameters
        dj_db, dj_dw = compute_gradient_logistic(X, y, w, b)   

        # Update Parameters using w, b, alpha and gradient
        w = w - alpha * dj_dw               
        b = b - alpha * dj_db               
      
        # Print cost every at intervals 10 times or as many iterations if < 10
        if(i%100 ==0):
            print("cost",compute_cost(X,y,w,b))
            print("w=" , w)
            print("b=" , b)
            print("--------------------------------------------------------------------------------------")


In [178]:
gradient_descent(x_train, y_train, W, 1, 0.01, 10000)

cost 8.887226594860442e-09
w= [0.99931227 1.00016709 0.99859844 0.99855501 0.99894819 0.99948848
 0.99951553 0.99951463]
b= 0.9977343127142196
--------------------------------------------------------------------------------------
cost 7.144795901195301e-09
w= [0.92944294 1.01295367 0.86057146 0.8587243  0.89430742 0.94998192
 0.95011052 0.9490022 ]
b= 0.7795029917365945
--------------------------------------------------------------------------------------
cost 5.839972415030411e-09
w= [0.85825175 1.01853492 0.72761155 0.72861393 0.79127161 0.90388774
 0.89905436 0.89537934]
b= 0.5778444188124017
--------------------------------------------------------------------------------------
cost 4.853347170320447e-09
w= [0.78707306 1.01793406 0.60110768 0.60888036 0.69072362 0.86139732
 0.84680548 0.83990085]
b= 0.39278664767366933
--------------------------------------------------------------------------------------
cost 4.10074776200015e-09
w= [0.71729127 1.01235665 0.48254412 0.50012251 0.593

cost 1.376313864742373e-09
w= [ 0.21953762  1.04301238 -0.23319059  0.02231603 -0.1730332   0.76612875
  0.24125867  0.41082476]
b= -0.8674742119917351
--------------------------------------------------------------------------------------
cost 1.3736455716390336e-09
w= [ 0.21915794  1.04601972 -0.23460972  0.02375411 -0.1752885   0.76821306
  0.24026029  0.4117735 ]
b= -0.8694148188577903
--------------------------------------------------------------------------------------
cost 1.3712207079812304e-09
w= [ 0.21881021  1.04883882 -0.23594813  0.0251164  -0.17740323  0.77013906
  0.23939224  0.41267209]
b= -0.8711816556227143
--------------------------------------------------------------------------------------
cost 1.369012630562707e-09
w= [ 0.21849023  1.05148109 -0.23721046  0.02640604 -0.17938763  0.77191861
  0.23863746  0.41352131]
b= -0.8727932548229972
--------------------------------------------------------------------------------------
cost 1.3669982516063785e-09
w= [ 0.2181945

cost 1.345335329198607e-09
w= [ 0.21437014  1.08622713 -0.25440996  0.04499533 -0.20637236  0.79188168
  0.23374861  0.42478585]
b= -0.890239737005307
--------------------------------------------------------------------------------------
cost 1.3451650653272426e-09
w= [ 0.21432903  1.08655318 -0.25456849  0.04519458 -0.2066398   0.79201505
  0.2337443   0.42488436]
b= -0.8903663037864668
--------------------------------------------------------------------------------------
cost 1.345006379428078e-09
w= [ 0.21429032  1.08685965 -0.25471698  0.04538278 -0.20689162  0.79213834
  0.23374084  0.42497645]
b= -0.8904842783600311
--------------------------------------------------------------------------------------
cost 1.344858457819068e-09
w= [ 0.21425387  1.08714773 -0.25485607  0.04556053 -0.20712873  0.79225232
  0.23373812  0.42506253]
b= -0.8905942628407444
--------------------------------------------------------------------------------------
cost 1.3447205468498206e-09
w= [ 0.21421954 

In [172]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [173]:
model.score(x_test,y_test)

0.7857142857142857

In [174]:
coefficients = model.coef_
intercept = model.intercept_

print("Coefficients:", coefficients)
print("Intercept:", intercept)

Coefficients: [[ 0.21255833  1.07113231 -0.24784154  0.04569683 -0.2008266   0.77815151
   0.23060673  0.42100175]]
Intercept: [-0.88612313]


In [185]:
y_pred_proba = model_output(x_train,y_train,[ 0.21379312 , 1.09077206,-0.25653641 , 0.04789389 ,-0.21015346 , 0.79345778,
  0.23374321 , 0.42607835],-0.8918761575970271)

In [186]:
from sklearn.metrics import log_loss
cost = log_loss(y_train, y_pred_proba)

print("Log-loss (Cost function):", cost)

Log-loss (Cost function): 0.46783513665245097
